[tool.black]
line-length = 88
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
known_third_party = [
    "django",
    "requests",
]
skip = [
    "migrations",
    "venv",
    "__pycache__",
]
