# Generated by Django 4.2.16 on 2024-10-29 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('read', 'Read'), ('unread', 'Unread')],
                        default='unread',
                        max_length=10,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='statuses',
                        to='channel.rssitem',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='user.user'
                    ),
                ),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
