# Generated by Django 4.2.16 on 2024-11-04 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='channel',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='channel.rsschannel',
            ),
        ),
        migrations.AddField(
            model_name='rsschannel',
            name='subscribed_channels',
            field=models.ManyToManyField(
                blank=True,
                related_name='subscribed_channels',
                through='channel.Subscription',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='itemstatus',
            name='item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='statuses',
                to='channel.rssitem',
            ),
        ),
        migrations.AddField(
            model_name='itemstatus',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='itemstatus',
            unique_together={('user', 'item')},
        ),
    ]
