# Generated by Django 4.2.16 on 2024-10-24 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    'username',
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                ('password', models.CharField(max_length=128)),
                (
                    'email',
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
            ],
        ),
    ]
